// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql"
	"time"
)

type Pago struct {
	IDPago          int32        `json:"id_pago"`
	IDSuscripciones int32        `json:"id_suscripciones"`
	Monto           string       `json:"monto"`
	FechaPago       time.Time    `json:"fecha_pago"`
	CreatedAt       sql.NullTime `json:"created_at"`
}

type Servicio struct {
	IDServicio int32        `json:"id_servicio"`
	Nombre     string       `json:"nombre"`
	Categoria  string       `json:"categoria"`
	CreatedAt  sql.NullTime `json:"created_at"`
}

type Subscripcione struct {
	IDSuscripciones  int32          `json:"id_suscripciones"`
	IDUsuario        int32          `json:"id_usuario"`
	IDServicio       int32          `json:"id_servicio"`
	Monto            string         `json:"monto"`
	FechaVencimiento time.Time      `json:"fecha_vencimiento"`
	FechaInicio      time.Time      `json:"fecha_inicio"`
	UsuarioCuenta    string         `json:"usuario_cuenta"`
	ContraseñaCuenta string         `json:"contraseña_cuenta"`
	Estado           sql.NullString `json:"estado"`
	CreatedAt        sql.NullTime   `json:"created_at"`
}

type Usuario struct {
	IDUsuario  int32        `json:"id_usuario"`
	Nombre     string       `json:"nombre"`
	Apellido   string       `json:"apellido"`
	Dni        string       `json:"dni"`
	Email      string       `json:"email"`
	Contraseña string       `json:"contraseña"`
	CreatedAt  sql.NullTime `json:"created_at"`
}
